fork = false

[font]
size = 12
# hinting = "full"
# edging = "antialias"

[[font.normal]]
family = "Lilex Nerd Font Mono"
style = "W400"

[font.features]
"Lilex Nerd Font Mono" = [ "+ss02", "+cv08", "+zero", "+cv15", "+cv06" ]
